### PR TITLE
Remove Azure section

### PR DESCRIPTION
**Pull request by ghost**
Note that I have not thoroughly compared between Carla's doc version and the version in the release notes here -- it is possible that the doc version still needs to be updated.

### CODE REVIEW

**Comment by axelaris** [comment]
I found some typos in https://www.suse.com/documentation/cloud-application-platform-1/book_cap_deployment/data/sec_cap_setup-kubernetes.html
It is easy to fix typos in Github, but how to fix typos on that page?

**Comment by ghost** [comment]
The content comes from https://github.com/suse/doc-cap , specifically:
https://github.com/SUSE/doc-cap/blob/develop/xml/cap_depl_azure.xml

You could definitely do a PR there as well, I am not 100% sure what workflow @cjschroder uses otherwise for that repo. But I guess you can use SUSE Bugzilla.

(However, before you merge this, I'd like to have some kind of go-ahead from Carla as well.)

**Comment by cjschroder** [comment]
I need to make some corrections to the Azure section of the Deployment guide, to sort out the differences between AKS and ACS. I'm working on this now, should have it up tomorrow. Then if there are still issues let me know. Opening an issue in the doc-cap repo is fine if you don't feel like messing with a PR.

**Comment by tomconte** [comment]
Hi everyone, I noticed this PR when looking for a place to contribute some steps to deploy CAP on top of AKS. I have published some notes below but I used a slightly different topology than the one in the doc (using a load balancer in front of the AKS nodes).

http://hypernephelist.com/2018/05/17/deploying-suse-cap-on-aks.html

Hope this helps anyway :)

**Comment by cjschroder** [comment]
I have published my changes. https://github.com/SUSE/doc-cap/pull/64/commits/938b14e356fce8f90e543465fa4af90b85f0e4c1

@tomconte That looks great. Load balancers are so much "fun" :)

**Comment by cjschroder** [comment]
@tomconte A couple of the issues with running CAP on AKS are no Ruby bindings on AKS, and no RBAC support. So your example disables RBAC, but what about Ruby?

**Comment by cjschroder** [comment]
Ah, it becomes clearer-- no CaaSP, so RBAC is not required. But what about Ruby?

**Comment by mook-as** [comment]
Ruby is only needed for [cloudstrap-azure](https://github.com/colstrom/cloudstrap-azure); it means we can script the installation better for our own purposes. We _could_ drop down to command line again for `aks` until that's ready, but that means there's more manual finicky bits and we're more likely to make mistakes in deployment.

**Comment by tomconte** [comment]
cloudstrap-azure looks pretty neat :) Is it a tool you guys use internally, or is it for customers also?

I suppose the Ruby SDK does not have support for AKS yet because it is still in preview. This should hopefully change in the next few weeks... 

Another possible way to simplify the deployment of dependencies could be to use an ARM template.

**Comment by axelaris** [comment]
I've added some fixes in new PR: https://github.com/SUSE/cap-release-notes/pull/30
However, still can't deploy CAP on top of Azure.
While deploying UAA I got the error:
```
$ helm install suse/uaa \
> --name susecf-uaa \
> --namespace uaa \
> --values scf-config-values.yaml

Error: release susecf-uaa failed: roles.rbac.authorization.k8s.io "configgin-role" is forbidden: attempt 
to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} 
PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], 
APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} 
PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["get"]}] user=&
{system:serviceaccount:kube-system:tiller b7904d1b-5b53-11e8-87c9-000d3a30a769 
[system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} 
ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]
```

UPD: the issue can be fixed by adding `auth: none` to scf-config-values.yaml

**Comment by cjschroder** [comment]
Thanks @axelaris, I'm adding your fixes to the CAP Deployment Guide.

@tomconte I like the idea of using tools native to the Azure platform.

**Comment by svollath** [comment]
We decided to keep the Notes-Azure (ACS), until AKS is fully documented within the product documentation.

**Comment by cjschroder** [comment]
Time to remove the Azure section. The AKS chapter has been published in the Deployment Guide.

**Comment by cjschroder** [comment]
@sknorr

**Comment by ghost** [comment]
@cjschroder Was on vacation, but glad that it finally happened.

**Pull request merged**
