### PR TITLE
Update published doc links

### PR DESCRIPTION
**Pull request by cjschroder**
which changed because the title of the CAP manual changed

### CODE REVIEW

**Review by btat — APPROVED** [review]
LGTM. Will we have any use for the `deployment-url` entity or can that be deleted now?

**Comment by cjschroder** [comment]
oops, I did a grep search for `deployment-url` and found many instances. This is not ready to merge yet, I need to make more corrections. Might be enough to change `deployment-url` to the Deployment section.

**Comment by cjschroder** [comment]
Ok done. what is the Travis error about? @sknorr

**Comment by ghost** [comment]
Thanks!

**Review by ghost — COMMENTED** [review]
r+

**Pull request merged**
