### PR TITLE
initial draft of 1.3 release

### PR DESCRIPTION
**Pull request by gaktive**
Troy to review the product messaging, along with anyone else with access to this repo for likely numerous typos/grammatical errors

### CODE REVIEW

**Review by gaktive — COMMENTED** [review]
LGTM

**Review by gaktive — COMMENTED** [review]
fixed app autoscaler

**Comment by cjschroder** [comment]
This looks luvverly. :+1:

**Comment by ghost** [comment]
@troytop @gaktive @cjschroder For the future, note the difference between attribute entry definition (`:entry:`) and attribute entry use (`{entry}`). The former must not appear within text, as it will not be resolved. Example from this PR: https://github.com/SUSE/cap-release-notes/pull/46/files#diff-72cee2b98f35b55bb996fa82a0740e2fR47
(I just corrected these.)

**Pull request merged**
